# Generated by Django 2.2.3 on 2019-07-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_page', '0002_auto_20190718_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptorate',
            name='code',
            field=models.CharField(max_length=2048, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='cryptorate',
            name='name',
            field=models.CharField(max_length=2048, verbose_name='Имя валюты'),
        ),
        migrations.AlterField(
            model_name='cryptorate',
            name='sell',
            field=models.FloatField(max_length=2048, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='code',
            field=models.CharField(max_length=2048, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='name',
            field=models.CharField(max_length=2048, verbose_name='Имя валюты'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='pursage',
            field=models.FloatField(verbose_name='Покупка'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='sell',
            field=models.FloatField(verbose_name='Продажа'),
        ),
    ]
